# Generated by Django 2.1.4 on 2018-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igp',
            old_name='org',
            new_name='org_rep',
        ),
        migrations.AddField(
            model_name='igp',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
