# Generated by Django 2.1.4 on 2018-12-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181206_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='igp',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ORG'),
        ),
    ]
