# Generated by Django 2.1.4 on 2018-12-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181206_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='description',
            new_name='desc',
        ),
    ]
