# Generated by Django 2.1.4 on 2018-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_igp_itype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
